# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8b322e8dcdf73317d574609a852ddc37424ac1890694b86ba48c369f7416473311f1896662f58034eb168178a7b2adeb76f581ec286f02aef09e2c38d21db37

test:
  secret_key_base: 2b9cdc7fda2255301d75eedcfe99ba0bddd354b0a7b4aebef7633e2567430a0296405c39f4c11f4f619248edadd5533ea39e0c5521353ec9aae51dc17cbfa821

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
